apiVersion: v1
kind: Template
labels:
  app: sshd
  template: sshd-imagestream
metadata:
  annotations:
    description: SSHD - ImageStream
      see https://github.com/faust64/docker-sshd
    iconClass: icon-openshift
    openshift.io/display-name: SSHD
    tags: sshd
  name: sshd-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in SSHD image
    name: sshd
