apiVersion: v1
kind: Template
labels:
  app: sshd
  template: sshd-ephemeral
metadata:
  annotations:
    description: SSHD - ephemeral
      see https://github.com/faust64/docker-sshd
    iconClass: icon-openshift
    openshift.io/display-name: SSHD
    tags: sshd
  name: sshd-ephemeral
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
     name: sshd
    name: sshd
  spec:
    replicas: 1
    selector:
      name: sshd
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: sshd
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 2222
            timeoutSeconds: 3
          name: sshd
          ports:
          - containerPort: 2222
            protocol: TCP
          readinessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 2222
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${SSHD_CPU_LIMIT}
              memory: ${SSHD_MEMORY_LIMIT}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - sshd
        from:
          kind: ImageStreamTag
          name: sshd:${SSHD_IMAGE_TAG}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: sshd://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
    name: sshd
  spec:
    ports:
    - name: mongo
      nodePort: 0
      port: 2222
      protocol: TCP
      targetPort: 2222
    selector:
      name: sshd
    type: ClusterIP
parameters:
- name: SSHD_CPU_LIMIT
  description: Maximum amount of CPU the container can use.
  displayName: CPU Limit
  required: true
  value: 50m
- name: SSHD_IMAGE_TAG
  description: The ImageStreamTag we should pull images from
  displayName: Tag
  required: true
  value: master
- name: SSHD_MEMORY_LIMIT
  description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  required: true
  value: 64Mi
